<?php

namespace FactelBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * PlanCtasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanCtasRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPlanCta(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select("emisor,factura,tip,mon,grup,usu")
        ->from("FactelBundle:PlanCuentas", "cta")
        ->join("cta.emisor", "emisor")
        ->join("cta.tipoCta", "tip")
        ->join("cta.codMoneda", "mon")
        ->join("cta.grupo", "grup")
        ->join("cta.codUsu", "usu")
        ->where('factura.id > 0')
        
                ;

                return $qb->getQuery()->getResult();
    }
}
