<?php

namespace FactelBundle\Entity;

/**
 * TipoCuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCuentaRepository extends \Doctrine\ORM\EntityRepository
{
}
